---
- name: Install filebeat
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: install epel-release
      yum:
         name: epel-release
         state: latest
    - block:
      - name: Install filebeat repo on centos 7
        get_url:
          url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.1.1-x86_64.rpm"
          dest: /tmp
        # shell: "curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.1.1-x86_64.rpm"
      - name: Install from rpm
        # shell: "rpm -vU filebeat-7.1.1-x86_64.rpm"
        yum:
           name: /tmp/filebeat-7.1.1-x86_64.rpm
           state: present
        notify: FILEBEAT_CENTOS_7
        # ignore_errors: true
      # when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
      - name: Start filebeat
        service:
          name: filebeat
          state: started
      - name: Enable filebeat
        service:
          name: filebeat
          enabled: yes
      - name: Short form task (in ansible 2+) necessitates backslash-escaped sequences
        replace: 
          path: /etc/filebeat/filebeat.yml 
          regexp: 'output.elasticsearch:' 
          replace: '#output.elasticsearch:'
      - name: Short form task (in ansible 2+) necessitates backslash-escaped sequences
        replace: 
          path: /etc/filebeat/filebeat.yml 
          regexp: '\ \ hosts: \["localhost:9200"\]' 
          replace: '  #hosts: ["localhost:9200"]'
      - name: Short form task (in ansible 2+) necessitates backslash-escaped sequences
        replace: 
          path: /etc/filebeat/filebeat.yml 
          regexp: '#output.logstash:' 
          replace: 'output.logstash:'
      - name: Short form task (in ansible 2+) necessitates backslash-escaped sequences
        replace: 
          path: /etc/filebeat/filebeat.yml 
          regexp: '\ \ #hosts: \["localhost:5044"\]' 
          replace: '  hosts: ["localhost:5044"]'
      
  handlers:
    - name: FILEBEAT_CENTOS_7
      systemd:
        name: filebeat
        state: restarted

