---
- name: Install filebeat
  hosts: all
  become: yes
  become_user: root
  tasks:
    - block:
      - name: Install filebeat repo on centos 6
        package: 
          name: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.1.1-x86_64.rpm"
          state: latest
        notify: FILEBEAT_CENTOS_6 
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
      ignore_errors: true
      


    - block:
      - name: Install filebeat repo on centos 7
        package: 
          name: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.1.1-x86_64.rpm"
          state: latest
        notify: FILEBEAT_CENTOS_7
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" 
      ignore_errors: true
    
  handlers:
    - name: FILEBEAT_CENTOS_6
      service:
        name: filebeat
        state: restarted
    - name: FILEBEAT_CENTOS_7
      systemd:
        name: filebeat
        state: restarted