---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Add users
      user:
        name: "{{ item}}"
        state: present
        generate_ssh_key: yes
      with_items:
        - shermat
        - toshmat
        - eshmamat
        - mamatqul
        - nurmat 